'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const core=require('../lib/local-core');
const OFFICIAL='UC_x5XG1OV2P6uZZ5FSM9Ttw';
const feed=(channel=OFFICIAL, extra='')=>`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom" xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/"><yt:channelId>${channel}</yt:channelId><entry><yt:videoId>abc123</yt:videoId><title>Hello</title><published>2026-09-15T00:00:00Z</published>${extra}</entry></feed>`;
test('official Google Developers Atom feed identity and required namespaces are enforced',()=>{assert.equal(core.parseAtom(feed(),OFFICIAL)[0].videoId,'abc123');for(const xml of [feed('OTHER'),'<feed xmlns="http://www.w3.org/2005/Atom" xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/"></feed>',feed().replace('xmlns:yt="http://www.youtube.com/xml/schemas/2015"','xmlns:yt="bad"'),feed().replace('</entry>','')])assert.throws(()=>core.parseAtom(xml,OFFICIAL));});
test('worksheet formula-like input is neutralized and import rejects formulas',()=>{for(const value of ['=1+1','+1','-1','@SUM(A1:A2)'])assert.equal(core.safeSpreadsheetText(value),`'${value}`);assert.throws(()=>core.validateWorkbookImport({revision:'1',profile:'daniel',missions:[],signals:[{id:'s',human_note:'=HYPERLINK("x")'}]},'1','daniel'));});
test('human backup is lossless for all human entities and excludes raw signal payload',()=>{const backup=core.humanBackup({profile:'daniel',missions:[{id:'m',title:'T',status:'DRAFT',source_id:'s',created_at:'x'}],signal_notes:[{video_id:'v',human_note:'note',created_at:'x'}],evidence:[{id:'e',source_id:null,body:'proof',created_at:'x'}],feedback:[{id:'f',piece_id:'m',date:'x',native_retention:'UP',icp_signal:'ICP',production_minutes:1,notes:'n',created_at:'x'}]});assert.equal(backup.version,3);assert.equal(backup.profile,'daniel');assert.equal(backup.evidence[0].body,'proof');assert.equal(backup.feedback[0].notes,'n');assert.equal(backup.signal_notes[0].video_id,'v');});
test('multi-source fetch prepares every batch before an atomic caller can write',async()=>{
 const requested=[];await assert.rejects(()=>core.fetchAllFeeds([{channel_id:OFFICIAL},{channel_id:'UCaaaaaaaaaaaaaaaaaaaa'}],async channel=>{requested.push(channel);if(channel!==OFFICIAL)throw new Error('network unavailable');return [];}),/network unavailable/);assert.deepEqual(requested,[OFFICIAL,'UCaaaaaaaaaaaaaaaaaaaa']);
});
