const test = require('node:test');
const assert = require('node:assert/strict');
const core = require('../lib/local-core');

test('RSS dedupe updates source data without replacing human fields', () => { const rows=[]; core.upsertSignal(rows,{videoId:'abc123',title:'new',publishedAt:'2026-09-21T00:00:00Z',views:null}); rows[0].humanNote='keep'; core.upsertSignal(rows,{videoId:'abc123',title:'changed',publishedAt:'2026-09-21T00:00:00Z',views:null}); assert.equal(rows.length,1); assert.equal(rows[0].title,'changed'); assert.equal(rows[0].humanNote,'keep'); assert.equal(rows[0].views,null); });
test('hostile, wrong namespace and wrong channel RSS are rejected', () => { assert.throws(()=>core.parseAtom('<!DOCTYPE x><feed/>','UCx')); assert.throws(()=>core.parseAtom('<feed xmlns="bad"></feed>','UCx')); assert.throws(()=>core.parseAtom('<feed xmlns="http://www.w3.org/2005/Atom"><entry><yt:channelId xmlns:yt="http://www.youtube.com/xml/schemas/2015">OTHER</yt:channelId></entry></feed>','UCx')); });
test('redirect hosts and timeout are fail closed', async () => { await assert.rejects(()=>core.fetchFeed('UC_x5XG1OV2P6uZZ5FSM9Ttw',{fetch:async()=>({url:'https://evil.test/a',ok:true,text:async()=>'<feed/>'})})); await assert.rejects(()=>core.fetchFeed('UC_x5XG1OV2P6uZZ5FSM9Ttw',{fetch:()=>new Promise(()=>{}) ,timeoutMs:10})); });
test('retention and source deletion remove derived data while preserving human missions', () => { const db={sources:[{id:'s'}],signals:[{sourceId:'s',fetchedAt:'2020-01-01',id:1}],evidence:[{sourceId:'s',id:1}],missions:[{id:'m',sourceId:'s',human:true}]}; core.deleteSource(db,'s'); assert.equal(db.signals.length,0); assert.equal(db.evidence.length,0); assert.equal(db.missions.length,1); });
test('workbook import rejects stale export revision and redacts secrets', () => { assert.throws(()=>core.assertRevision('old','new')); assert.equal(core.redact('key=secret-token'), 'key=[REDACTED]'); });
test('scheduled run is idempotent and backup human-only omits expired source-derived data', () => { const state={lastScheduledDay:null}; assert.equal(core.claimScheduled(state,'2026-09-21'),true); assert.equal(core.claimScheduled(state,'2026-09-21'),false); const b=core.humanBackup({signals:[{fetchedAt:'2020-01-01'}],missions:[{title:'Draft'}]}); assert.equal((b.signal_notes||[]).length,0); assert.equal(b.missions.length,1); });

