'use strict';
const ATOM='http://www.w3.org/2005/Atom';
const YT='http://www.youtube.com/xml/schemas/2015';
const MEDIA='http://search.yahoo.com/mrss/';
const MAX_BYTES=2*1024*1024, MAX_ELEMENTS=2000, MAX_DEPTH=64;
const PROFILES=Object.freeze({daniel:{id:'daniel',displayName:'Daniel',owner:'daniel'},sebastian:{id:'sebastian',displayName:'Sebastián',owner:'sebastian'}});
function profileDefinition(value){const profile=PROFILES[String(value||'').toLowerCase()];if(!profile)throw new Error('unknown profile');return profile;}
function redact(value){return String(value??'').replace(/(key|token|secret|authorization|api[_-]?key)\s*[=:]\s*[^\s,;]+/ig,'$1=[REDACTED]').replace(/[A-Za-z]:\\[^\r\n]*/g,'[PATH]').replace(/\/[^\s:]+(?:\/[^\s:]+)+/g,'[PATH]');}
function safeError(error){const raw=redact(error?.message||error||'operation failed');if(/traceback|\bat \S+ \(|\.py:\d+|\.js:\d+/i.test(raw))return 'operation failed';return raw.slice(0,240);}
function assertRevision(expected,actual){if(String(expected)!==String(actual))throw new Error('STALE_WORKBOOK: export revision no longer matches local database');}
function safeSpreadsheetText(value){const text=String(value??'');return /^[=+\-@]/.test(text)?`'${text}`:text;}
function decodeXml(text){return String(text).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'");}
function parseAtom(xml,expectedChannel){
 if(typeof xml!=='string'||Buffer.byteLength(xml)>MAX_BYTES)throw new Error('invalid feed size');if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw new Error('unsafe XML');
 const tokens=xml.match(/<!--[\s\S]*?-->|<!\[CDATA\[[\s\S]*?\]\]>|<\?[^?]*\?>|<[^>]+>|[^<]+/g);if(!tokens||tokens.join('')!==xml)throw new Error('malformed XML');const stack=[];let count=0;
 for(const token of tokens){if(!token.startsWith('<')||/^<!--|^<\?|^<!\[CDATA/.test(token))continue;if(/^<\//.test(token)){const name=token.slice(2,-1).trim(),node=stack.pop();if(!node||node!==name)throw new Error('malformed XML');continue;}if(/^<!/.test(token))throw new Error('unsafe XML');const self=/\/>$/.test(token),name=token.slice(1,self?-2:-1).trim().split(/\s/,1)[0];if(++count>MAX_ELEMENTS||stack.length>=MAX_DEPTH)throw new Error('XML depth/element limit exceeded');if(!stack.length&&name!=='feed')throw new Error('wrong Atom namespace');if(!self)stack.push(name);}
 if(stack.length)throw new Error('malformed XML');const root=xml.match(/<feed\b([^>]*)>/);if(!root||!/xmlns\s*=\s*(['"])http:\/\/www\.w3\.org\/2005\/Atom\1/.test(root[1])||!/xmlns:yt\s*=\s*(['"])http:\/\/www\.youtube\.com\/xml\/schemas\/2015\1/.test(root[1])||!/xmlns:media\s*=\s*(['"])http:\/\/search\.yahoo\.com\/mrss\/\1/.test(root[1]))throw new Error('required Atom/YouTube/media namespaces missing');
 const feedHeader=xml.slice(0,xml.indexOf('<entry'));const channelMatch=feedHeader.match(/<yt:channelId(?:\s[^>]*)?>([^<]+)<\/yt:channelId>/);const channel=channelMatch&&decodeXml(channelMatch[1].trim());if(channel!==expectedChannel&&!(channel===expectedChannel.slice(2)&&feedHeader.includes('https://www.youtube.com/channel/'+expectedChannel)))throw new Error('wrong or missing channel');return [...xml.matchAll(/<entry\b[\s\S]*?<\/entry>/g)].map(m=>{const e=m[0],video=(e.match(/<yt:videoId(?:\s[^>]*)?>([^<]+)<\/yt:videoId>/)||[])[1];if(!video)throw new Error('entry missing video id');return {videoId:decodeXml(video.trim()),title:decodeXml((e.match(/<title(?:\s[^>]*)?>([\s\S]*?)<\/title>/)||[])[1]||''),publishedAt:(e.match(/<published(?:\s[^>]*)?>([^<]+)<\/published>/)||[])[1]||null,views:null};});
}
async function fetchFeed(channelId,{fetch=globalThis.fetch,timeoutMs=10000}={}){
 if(!/^UC[\w-]{20,}$/.test(channelId))throw new Error('invalid channel ID');const controller=new AbortController();let timer;
 const timedOut=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(new Error('feed request timed out'));},timeoutMs);});
 const request=Promise.resolve().then(()=>fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(channelId)}`,{signal:controller.signal,redirect:'error'}));
 // The rejection observer prevents a late non-cooperative fetch rejection from becoming unhandled.
 request.catch(()=>{});
 try{const r=await Promise.race([request,timedOut]);if(!r.ok||new URL(r.url).hostname!=='www.youtube.com')throw new Error('feed request rejected');return parseAtom(await r.text(),channelId);}catch(e){throw new Error(e?.name==='AbortError'?'feed request timed out':redact(e?.message));}finally{clearTimeout(timer);}
}
async function fetchAllFeeds(sources,fetcher=fetchFeed){const batches=[];for(const source of sources)batches.push({source,entries:await fetcher(source.channel_id)});return batches;}
function upsertSignal(rows,input){if(!/^[\w-]{6,}$/.test(input.videoId))throw new Error('invalid video ID');const existing=rows.find(x=>x.videoId===input.videoId),safe={videoId:input.videoId,title:String(input.title||''),publishedAt:input.publishedAt||null,views:input.views??null,updatedAt:new Date().toISOString()};if(existing){Object.assign(existing,safe);return{record:existing,created:false};}const record={id:crypto.randomUUID(),humanNote:'',...safe};rows.push(record);return{record,created:true};}
function deleteSource(db,id){db.sources=db.sources.filter(x=>x.id!==id);db.signals=db.signals.filter(x=>x.sourceId!==id);db.evidence=db.evidence.filter(x=>x.sourceId!==id);}
function claimScheduled(state,day){if(state.lastScheduledDay===day)return false;state.lastScheduledDay=day;return true;}
function humanBackup(db){return {version:3,profile:db.profile,config:(db.config||[]).map(({k,v})=>({k,v})),missions:(db.missions||[]).map(({id,title,status,created_at})=>({id,title,status,created_at})),signal_notes:(db.signal_notes||db.signals||[]).filter(x=>x.human_note||x.humanNote).map(x=>({video_id:x.video_id||x.videoId,human_note:x.human_note||x.humanNote,created_at:x.created_at||null})),evidence:(db.evidence||[]).map(({id,body,created_at,source_id,source_reference})=>({id,body,created_at,source_reference:source_reference||(source_id?'curated-source':null)})),feedback:(db.feedback||[]).map(({id,piece_id,date,native_retention,icp_signal,production_minutes,notes,created_at})=>({id,piece_id,date,native_retention,icp_signal,production_minutes,notes,created_at}))};}
function validateWorkbookImport(data,revision,profile){assertRevision(data.revision,revision);if(profile&&data.profile!==profile)throw new Error('workbook profile does not match selected profile');for(const group of ['missions','signals','feedback'])for(const row of data[group]||[])for(const value of Object.values(row))if(typeof value==='string'&&value.startsWith('='))throw new Error('workbook formulas are not importable');return data;}
function sanitizedEvidence(text){const value=String(text||'').trim();if(!value||value.length>8000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))throw new Error('invalid evidence body');return value;}
module.exports={redact,safeError,assertRevision,safeSpreadsheetText,upsertSignal,parseAtom,fetchFeed,fetchAllFeeds,deleteSource,claimScheduled,humanBackup,validateWorkbookImport,profileDefinition,PROFILES,sanitizedEvidence,ATOM,YT,MEDIA};